"""
Built-in site profiles for NY disclosure visibility audits (research).
Listing a site does not assert personalized pricing or legal noncompliance.
"""

from __future__ import annotations

from typing import Literal

from dataclasses import dataclass

StrategyKind = Literal["food_delivery", "grocery_retail", "travel", "ticketing", "generic"]

CAT_FOOD_DEL = "food_delivery"
CAT_GROCERY = "grocery_retail"
CAT_TRAVEL = "travel_lodging"
CAT_TICKET = "ticketing_reservations"

CATEGORY_LABELS: dict[str, str] = {
    CAT_FOOD_DEL: "Food delivery",
    CAT_GROCERY: "Grocery / retail",
    CAT_TRAVEL: "Travel / lodging / flights",
    CAT_TICKET: "Ticketing",
}


@dataclass(frozen=True)
class SiteProfile:
    platform_name: str
    category: str
    category_slug: str
    strategy_kind: StrategyKind
    homepage_url: str
    target_urls: tuple[str, ...]
    likely_entry_points: tuple[str, ...]
    likely_price_page_types: str
    requires_login: bool
    address_required: bool
    search_required: bool
    cart_supported: bool
    notes: str
    enabled: bool
    pilot_priority: bool


def _sp(
    name: str,
    category_slug: str,
    strat: StrategyKind,
    home: str,
    targets: tuple[str, ...],
    *,
    pilot: bool,
    entry: tuple[str, ...] = ("homepage",),
    price_types: str = "homepage",
    login: bool = False,
    addr: bool = False,
    search: bool = False,
    cart: bool = True,
    notes: str = "",
    enabled: bool = True,
) -> SiteProfile:
    return SiteProfile(
        platform_name=name,
        category=CATEGORY_LABELS[category_slug],
        category_slug=category_slug,
        strategy_kind=strat,
        homepage_url=home,
        target_urls=targets,
        likely_entry_points=entry,
        likely_price_page_types=price_types,
        requires_login=login,
        address_required=addr,
        search_required=search,
        cart_supported=cart,
        notes=notes,
        enabled=enabled,
        pilot_priority=pilot,
    )


# Seed URLs are starting points; replace with study-specific URLs per IRB/terms.
SITE_REGISTRY: tuple[SiteProfile, ...] = (
    # Food delivery
    _sp(
        "DoorDash",
        CAT_FOOD_DEL,
        "food_delivery",
        "https://www.doordash.com",
        ("https://www.doordash.com", "https://www.doordash.com/restaurants-near-me/"),
        pilot=True,
        entry=("homepage", "restaurant_search", "address_prompt_likely"),
        price_types="menu | cart | checkout",
        addr=True,
        search=True,
        notes="Address gate likely; cart/checkout for fee lines; SPA-heavy.",
    ),
    _sp(
        "Uber Eats",
        CAT_FOOD_DEL,
        "food_delivery",
        "https://www.ubereats.com",
        ("https://www.ubereats.com", "https://www.ubereats.com/feed"),
        pilot=True,
        entry=("homepage", "feed"),
        price_types="menu | cart | checkout",
        addr=True,
        notes="Delivery location prompts; promos may vary by account.",
    ),
    _sp(
        "Grubhub",
        CAT_FOOD_DEL,
        "food_delivery",
        "https://www.grubhub.com",
        ("https://www.grubhub.com",),
        pilot=True,
        entry=("homepage", "search"),
        price_types="menu | checkout",
        addr=True,
        notes="Marketplace; checkout totals.",
    ),
    _sp(
        "Postmates",
        CAT_FOOD_DEL,
        "food_delivery",
        "https://postmates.com",
        ("https://postmates.com",),
        pilot=False,
        entry=("homepage",),
        price_types="redirect_or_ubereats",
        notes="Often redirects to Uber Eats; app-like flows.",
    ),
    _sp(
        "Slice",
        CAT_FOOD_DEL,
        "food_delivery",
        "https://www.slicelife.com",
        ("https://www.slicelife.com",),
        pilot=False,
        entry=("homepage", "pizza_search"),
        price_types="menu | checkout",
        addr=True,
        notes="Local pizza orders; address for delivery quote.",
    ),
    _sp(
        "Too Good To Go",
        CAT_FOOD_DEL,
        "food_delivery",
        "https://www.toogoodtogo.com",
        ("https://www.toogoodtogo.com", "https://www.toogoodtogo.com/en-us"),
        pilot=False,
        entry=("homepage", "map_listings"),
        price_types="surprise_bag | checkout",
        notes="Surplus pricing; location-based inventory.",
    ),
    # Grocery / retail
    _sp(
        "Instacart",
        CAT_GROCERY,
        "grocery_retail",
        "https://www.instacart.com",
        ("https://www.instacart.com", "https://www.instacart.com/store/"),
        pilot=True,
        entry=("store", "search"),
        price_types="pdp | cart | checkout",
        addr=True,
        search=True,
        notes="Delivery address gate; fees at checkout.",
    ),
    _sp(
        "Walmart",
        CAT_GROCERY,
        "grocery_retail",
        "https://www.walmart.com",
        ("https://www.walmart.com", "https://www.walmart.com/search?q=milk"),
        pilot=True,
        entry=("search", "pdp"),
        price_types="search | pdp | cart",
        search=True,
        notes="Pickup/delivery; W+ pricing context possible.",
    ),
    _sp(
        "Target",
        CAT_GROCERY,
        "grocery_retail",
        "https://www.target.com",
        ("https://www.target.com", "https://www.target.com/s?searchTerm=milk"),
        pilot=True,
        entry=("search", "pdp"),
        price_types="search | cart | checkout",
        search=True,
        notes="Circle offers; cart summary.",
    ),
    _sp(
        "Amazon",
        CAT_GROCERY,
        "grocery_retail",
        "https://www.amazon.com",
        ("https://www.amazon.com", "https://www.amazon.com/s?k=cereal"),
        pilot=True,
        entry=("search", "pdp"),
        price_types="search | pdp | cart | checkout",
        search=True,
        notes="Buy Box; many dynamic promos; heavy SPA.",
    ),
    _sp(
        "FreshDirect",
        CAT_GROCERY,
        "grocery_retail",
        "https://www.freshdirect.com",
        ("https://www.freshdirect.com",),
        pilot=False,
        entry=("homepage", "zip_gate"),
        price_types="catalog | cart",
        addr=True,
        notes="ZIP/address gate common for delivery slot pricing.",
    ),
    _sp(
        "Wegmans",
        CAT_GROCERY,
        "grocery_retail",
        "https://www.wegmans.com",
        ("https://www.wegmans.com",),
        pilot=False,
        entry=("homepage", "store_search"),
        price_types="pdp | cart",
        addr=True,
        notes="Regional; online order flows.",
    ),
    _sp(
        "Mercato",
        CAT_GROCERY,
        "grocery_retail",
        "https://www.mercato.com",
        ("https://www.mercato.com",),
        pilot=False,
        entry=("homepage", "store"),
        price_types="cart | checkout",
        addr=True,
        notes="Local grocers; delivery fees vary.",
    ),
    _sp(
        "Whole Foods Market",
        CAT_GROCERY,
        "grocery_retail",
        "https://www.wholefoodsmarket.com",
        ("https://www.wholefoodsmarket.com",),
        pilot=False,
        entry=("homepage",),
        price_types="shop_amazon_integration",
        notes="Often ties to Amazon; Prime pricing context.",
    ),
    _sp(
        "Lidl",
        CAT_GROCERY,
        "grocery_retail",
        "https://www.lidl.com",
        ("https://www.lidl.com",),
        pilot=False,
        entry=("homepage", "weekly_ad"),
        price_types="circular | store",
        notes="US site; regional pricing.",
    ),
    _sp(
        "Amazon Fresh",
        CAT_GROCERY,
        "grocery_retail",
        "https://www.amazon.com/fresh",
        ("https://www.amazon.com/fresh",),
        pilot=False,
        entry=("fresh_home",),
        price_types="browse | cart",
        addr=True,
        notes="ZIP-gated availability; Amazon account context.",
    ),
    _sp(
        "Imperfect Foods",
        CAT_GROCERY,
        "grocery_retail",
        "https://www.imperfectfoods.com",
        ("https://www.imperfectfoods.com",),
        pilot=False,
        entry=("homepage", "signup_or_zip"),
        price_types="subscription_cart",
        addr=True,
        notes="Subscription box; address for delivery window.",
    ),
    _sp(
        "Kroger",
        CAT_GROCERY,
        "grocery_retail",
        "https://www.kroger.com",
        ("https://www.kroger.com",),
        pilot=False,
        entry=("homepage", "store_pickup"),
        price_types="search | cart",
        addr=True,
        notes="Store selection; loyalty pricing possible.",
    ),
    # Travel
    _sp(
        "Tripadvisor",
        CAT_TRAVEL,
        "travel",
        "https://www.tripadvisor.com",
        ("https://www.tripadvisor.com",),
        pilot=False,
        entry=("search_widget", "hotel_listings"),
        price_types="meta_compare | partner_redirect",
        search=True,
        notes="Often redirects to OTA for final price.",
    ),
    _sp(
        "Airbnb",
        CAT_TRAVEL,
        "travel",
        "https://www.airbnb.com",
        ("https://www.airbnb.com", "https://www.airbnb.com/s/homes"),
        pilot=True,
        entry=("search", "listing"),
        price_types="listing | checkout",
        search=True,
        notes="Total before pay; service fee breakdown.",
    ),
    _sp(
        "Booking.com",
        CAT_TRAVEL,
        "travel",
        "https://www.booking.com",
        ("https://www.booking.com", "https://www.booking.com/searchresults.html?ss=New+York"),
        pilot=True,
        entry=("search", "results"),
        price_types="property | checkout",
        search=True,
        notes="Member deals; fee lines near checkout.",
    ),
    _sp(
        "Expedia",
        CAT_TRAVEL,
        "travel",
        "https://www.expedia.com",
        ("https://www.expedia.com", "https://www.expedia.com/Hotel-Search?destination=New+York"),
        pilot=True,
        entry=("package_search",),
        price_types="search | checkout",
        search=True,
        notes="Bundled travel; upsells.",
    ),
    _sp(
        "Hotels.com",
        CAT_TRAVEL,
        "travel",
        "https://www.hotels.com",
        ("https://www.hotels.com",),
        pilot=False,
        entry=("search",),
        price_types="results | checkout",
        search=True,
        notes="Rewards nights; taxes/fees at pay.",
    ),
    _sp(
        "Vrbo",
        CAT_TRAVEL,
        "travel",
        "https://www.vrbo.com",
        ("https://www.vrbo.com",),
        pilot=False,
        entry=("search", "listing"),
        price_types="quote | checkout",
        search=True,
        notes="Cleaning/service fees on listing.",
    ),
    _sp(
        "Kayak",
        CAT_TRAVEL,
        "travel",
        "https://www.kayak.com",
        ("https://www.kayak.com",),
        pilot=False,
        entry=("flight_hotel_search",),
        price_types="meta | redirect",
        search=True,
        notes="Final price often on airline/OTA site.",
    ),
    _sp(
        "Google Flights",
        CAT_TRAVEL,
        "travel",
        "https://www.google.com/travel/flights",
        ("https://www.google.com/travel/flights",),
        pilot=True,
        entry=("flight_search",),
        price_types="itinerary | book_with_partner",
        search=True,
        notes="Lightweight search UI; partner site for purchase.",
    ),
    _sp(
        "United Airlines",
        CAT_TRAVEL,
        "travel",
        "https://www.united.com",
        ("https://www.united.com", "https://www.united.com/en/us/flight-search"),
        pilot=True,
        entry=("flight_search",),
        price_types="fare_select | checkout",
        search=True,
        notes="Airline fare rules; logged-in vs guest may differ.",
    ),
    _sp(
        "American Airlines",
        CAT_TRAVEL,
        "travel",
        "https://www.aa.com",
        ("https://www.aa.com", "https://www.aa.com/booking/find-flights"),
        pilot=False,
        entry=("flight_search",),
        price_types="select | pay",
        search=True,
        notes="AAdvantage pricing possible when logged in.",
    ),
    _sp(
        "Delta Air Lines",
        CAT_TRAVEL,
        "travel",
        "https://www.delta.com",
        ("https://www.delta.com", "https://www.delta.com/flight-search/book-a-flight"),
        pilot=False,
        entry=("flight_search",),
        price_types="select | trip_summary",
        search=True,
        notes="SkyMiles fares when authenticated.",
    ),
    _sp(
        "Lufthansa",
        CAT_TRAVEL,
        "travel",
        "https://www.lufthansa.com",
        ("https://www.lufthansa.com",),
        pilot=False,
        entry=("flight_search",),
        price_types="fare | pay",
        search=True,
        notes="International carrier; cookie/consent heavy.",
    ),
    _sp(
        "Southwest Airlines",
        CAT_TRAVEL,
        "travel",
        "https://www.southwest.com",
        ("https://www.southwest.com", "https://www.southwest.com/air/booking/"),
        pilot=False,
        entry=("flight_search",),
        price_types="select | purchase",
        search=True,
        notes="Fare rules; no bag fee on some fares.",
    ),
    # Ticketing
    _sp(
        "Ticketmaster",
        CAT_TICKET,
        "ticketing",
        "https://www.ticketmaster.com",
        ("https://www.ticketmaster.com", "https://www.ticketmaster.com/discover/concerts"),
        pilot=True,
        entry=("event_search", "seat_map"),
        price_types="ticket_select | fees | checkout",
        notes="Fees breakdown; high bot protection possible.",
    ),
    _sp(
        "StubHub",
        CAT_TICKET,
        "ticketing",
        "https://www.stubhub.com",
        ("https://www.stubhub.com",),
        pilot=True,
        entry=("event", "listing"),
        price_types="all_in_price | checkout",
        notes="Secondary market; fee disclosure at checkout.",
    ),
    _sp(
        "SeatGeek",
        CAT_TICKET,
        "ticketing",
        "https://seatgeek.com",
        ("https://seatgeek.com",),
        pilot=True,
        entry=("event", "deal_score"),
        price_types="listing | checkout",
        notes="Fees at purchase step.",
    ),
    _sp(
        "AXS",
        CAT_TICKET,
        "ticketing",
        "https://www.axs.com",
        ("https://www.axs.com",),
        pilot=False,
        entry=("events", "checkout"),
        price_types="ticket | fees",
        notes="Venue/partner flows; login sometimes required.",
    ),
)


def normalize_category_filter(s: str) -> str | None:
    s = s.strip().lower().replace(" ", "_").replace("-", "_")
    aliases: dict[str, str] = {
        "food": CAT_FOOD_DEL,
        "food_delivery": CAT_FOOD_DEL,
        "delivery": CAT_FOOD_DEL,
        "grocery": CAT_GROCERY,
        "grocery_retail": CAT_GROCERY,
        "retail": CAT_GROCERY,
        "travel": CAT_TRAVEL,
        "lodging": CAT_TRAVEL,
        "flights": CAT_TRAVEL,
        "ticket": CAT_TICKET,
        "ticketing": CAT_TICKET,
        "tickets": CAT_TICKET,
    }
    if s in CATEGORY_LABELS:
        return s
    return aliases.get(s)
